# Generated by Django 2.2 on 2019-04-10 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a room name.', max_length=200)),
                ('host_token', models.CharField(max_length=600)),
                ('host_refresh_token', models.CharField(max_length=600)),
            ],
        ),
    ]
