# Generated by Django 2.2 on 2019-04-29 00:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.crypto
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a room name.', max_length=200)),
                ('code', models.CharField(default=django.utils.crypto.get_random_string, max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.CharField(max_length=200)),
                ('track_name', models.CharField(max_length=200)),
                ('track_artist', models.CharField(max_length=200)),
                ('track_art', models.CharField(max_length=200)),
                ('track_length', models.IntegerField()),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(help_text='Enter a your display name.', max_length=200)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.Room')),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(help_text='Enter a your display name.', max_length=200)),
                ('host_token', models.CharField(max_length=600)),
                ('host_refresh_token', models.CharField(max_length=600)),
                ('room', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='room.Room')),
            ],
        ),
    ]
