# Generated by Django 2.2 on 2019-04-15 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='host_refresh_token',
        ),
        migrations.RemoveField(
            model_name='room',
            name='host_token',
        ),
        migrations.AddField(
            model_name='room',
            name='code',
            field=models.CharField(default='000000', max_length=6),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(help_text='Enter a your display name.', max_length=200)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.Room')),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(help_text='Enter a your display name.', max_length=200)),
                ('host_token', models.CharField(max_length=600)),
                ('host_refresh_token', models.CharField(max_length=600)),
                ('room', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='room.Room')),
            ],
        ),
    ]
