# Generated by Django 2.2 on 2019-04-11 00:18

from django.db import migrations, models
import django.db.models.deletion
import room.models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_auto_20190410_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='room',
            field=models.OneToOneField(default=room.models.Room.get_new, on_delete=django.db.models.deletion.CASCADE, to='room.Room'),
        ),
    ]
