# Generated by Django 2.2 on 2019-04-22 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_auto_20190422_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default='2T4VPM', max_length=6),
        ),
    ]
