# Generated by Django 2.2 on 2019-04-22 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_auto_20190422_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default='K2X185', max_length=6),
        ),
    ]
