# Generated by Django 2.2 on 2019-04-22 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0007_auto_20190422_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default='000000', max_length=6),
        ),
    ]
