# Generated by Django 2.2 on 2019-04-23 00:24

from django.db import migrations, models
import django.utils.crypto


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0008_auto_20190422_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default=django.utils.crypto.get_random_string, max_length=6),
        ),
    ]
